export const GET_MOVIE_LIST = 'GET_MOVIE_LIST';
export const GET_MOVIE_IMAGE = 'GET_FILM_IMAGE';
export const GET_MOVIE_NAME = 'GET_FILM_NAME';
export const GET_MOVIE_DESCRIPTION = 'GET_FILM_DESCRIPTION';